version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=datatea
      - POSTGRES_USER=datatea
      - POSTGRES_PASSWORD=dev
  backend:
    image: python:latest
    working_dir: /code
    command: bash -c "
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=datatea
      - DB_USERNAME=datatea
      - DB_PASSWORD=dev
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONUNBUFFERED=1
    volumes:
      - ./datatea-backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: node:latest
    volumes:
      - ./datatea-frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on: 
      - backend
    environment:
      - VUE_APP_URL_ENDPOINT=http://localhost:8000/teas