version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=datatea
      - POSTGRES_USER=datatea
      - POSTGRES_PASSWORD=dev
  backend:
    build: datatea-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./datatea-backend:/sources
    ports:
      - "8000:8000"
    depends_on:
      - db